-- Script para corrigir a tabela Reviews que não foi criada pela migration
-- Execute este script no seu banco de dados PostgreSQL

-- Primeiro, verificar se a tabela Reviews já existe
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'Reviews'
    ) THEN
        -- Criar a tabela Reviews se ela não existir
        CREATE TABLE "Reviews" (
            "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            "EntityId" integer NOT NULL,
            "EntityType" character varying(50) NOT NULL,
            "ReviewerId" integer NOT NULL,
            "Score" integer NOT NULL,
            "Comment" character varying(1000) NOT NULL,
            "CreatedAt" timestamp without time zone NOT NULL,
            "IsVerified" boolean NOT NULL DEFAULT false,
            "WorshipPresenceId" integer NULL,
            "VerifiedAt" timestamp without time zone NULL,
            CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_Reviews_member_ReviewerId" FOREIGN KEY ("ReviewerId") 
                REFERENCES postgres.member(id) ON DELETE RESTRICT,
            CONSTRAINT "FK_Reviews_worship_presences_WorshipPresenceId" FOREIGN KEY ("WorshipPresenceId") 
                REFERENCES postgres.worship_presences(id) ON DELETE SET NULL
        );

        -- Criar índices
        CREATE INDEX "IX_Reviews_ReviewerId" ON "Reviews" ("ReviewerId");
        CREATE INDEX "IX_Reviews_WorshipPresenceId" ON "Reviews" ("WorshipPresenceId");

        RAISE NOTICE 'Tabela Reviews criada com sucesso!';
    ELSE
        RAISE NOTICE 'Tabela Reviews já existe, nenhuma ação necessária.';
    END IF;
END
$$;
