// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyChurch.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyChurch.Infrastructure.Migrations
{
    [DbContext(typeof(MyChurchDbContext))]
    [Migration("20250610194418_AddTableToVerseofTheDay")]
    partial class AddTableToVerseofTheDay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventParticipants", b =>
                {
                    b.Property<int>("event_id")
                        .HasColumnType("int");

                    b.Property<int>("member_id")
                        .HasColumnType("int");

                    b.HasKey("event_id", "member_id");

                    b.HasIndex("member_id");

                    b.ToTable("event_participants", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Number")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("street");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("address", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("identification_code");

                    b.Property<DateTime?>("LastMaintenance")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_maintenance");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextMaintenance")
                        .HasColumnType("timestamp")
                        .HasColumnName("next_maintenance");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("purchase_date");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("responsible");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.Property<DateTime?>("WarrantyUntil")
                        .HasColumnType("timestamp")
                        .HasColumnName("warranty_until");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("asset", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.BankingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account");

                    b.Property<string>("AccountDigit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("account_digit");

                    b.Property<string>("AccountType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_type");

                    b.Property<string>("Agency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("agency");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("HolderDocument")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("holder_document");

                    b.Property<string>("HolderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("holder_name");

                    b.Property<string>("PixKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pix_key");

                    b.Property<string>("PixKeyType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pix_key_type");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("banking_info", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("testament");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("books", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("chapters", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Hymn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("Lyrics")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("lyrics");

                    b.Property<string>("LyricsAuthor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lyrics_author");

                    b.Property<string>("MelodyAuthor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("melody_author");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("hymns", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("verse_number");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("verses", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("publisher");

                    b.HasKey("Id");

                    b.ToTable("versions", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CashFlowCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("cash_flow_categories", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CashFlowEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MemberId");

                    b.ToTable("cash_flow_entries", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Church", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("AsaasCustomerId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("asaas_customer_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Document")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("document");

                    b.Property<string>("LogoFileName")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("logo_file_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<decimal>("PlatformFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,4)")
                        .HasDefaultValue(0.05m)
                        .HasColumnName("platform_fee");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("church", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CreditCardInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("card_brand");

                    b.Property<string>("CardHash")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("card_hash");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("Last4Digits")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("last4digits");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("credit_card_info", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<decimal>("PlatformFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("platform_fee");

                    b.Property<DateTime?>("TransferredAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("donation", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("finish_date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<bool>("RequiresParticipantList")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_participant_list");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("event", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.EventNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_notification", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.EventRecurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("int")
                        .HasColumnName("frequency");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("recurrence_end_date");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("int")
                        .HasColumnName("recurrence_type");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_recurrence", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.FeedLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("FeedPostId")
                        .HasColumnType("integer")
                        .HasColumnName("feed_post_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("FeedPostId", "MemberId")
                        .IsUnique();

                    b.ToTable("feed_likes", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.FeedPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.HasIndex("MemberId");

                    b.ToTable("feed_posts", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("BaptizedDate")
                        .HasColumnType("date")
                        .HasColumnName("baptized_date");

                    b.Property<string>("BirthCity")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("birth_city");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthState")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("birth_state");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBaptized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_baptized");

                    b.Property<bool>("IsTither")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_tither");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marital_status");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("date")
                        .HasColumnName("member_since");

                    b.Property<string>("Ministry")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ministry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ChurchId");

                    b.ToTable("member", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.MemberDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("member_document", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BillingType")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("billing_type");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp")
                        .HasColumnName("date");

                    b.Property<int?>("DonationId")
                        .HasColumnType("int")
                        .HasColumnName("donation_id");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_status");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("DonationId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("payment", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Branches")
                        .HasColumnType("int")
                        .HasColumnName("branches");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<int>("MaxEvents")
                        .HasColumnType("int")
                        .HasColumnName("max_events");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int")
                        .HasColumnName("max_members");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("int")
                        .HasColumnName("max_storage_gb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.ToTable("plan", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_date");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("external_reference");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId")
                        .IsUnique();

                    b.HasIndex("PlanId");

                    b.ToTable("subscription", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.TransferHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("ChurchId")
                        .HasColumnType("int")
                        .HasColumnName("church_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("transfer_history", "postgres");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.VerseOfTheDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("VerseText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verse_text");

                    b.HasKey("Id");

                    b.ToTable("verses_of_the_day", "postgres");
                });

            modelBuilder.Entity("EventParticipants", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChurch.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("member_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Asset", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany("Assets")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.BankingInfo", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Book", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Bible.Version", "Version")
                        .WithMany("Books")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Chapter", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Bible.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Verse", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Bible.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CashFlowCategory", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany("CashFlowCategories")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CashFlowEntry", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.CashFlowCategory", "Category")
                        .WithMany("CashFlowEntries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany("CashFlowEntries")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChurch.Domain.Entities.Member", "Member")
                        .WithMany("CashFlowEntries")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Church");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Church", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Address", "Address")
                        .WithOne("Church")
                        .HasForeignKey("MyChurch.Domain.Entities.Church", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CreditCardInfo", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Member", "Member")
                        .WithMany("CreditCardInfos")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Donation", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Member", "Member")
                        .WithMany("Donations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Event", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany("Events")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.EventNotification", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Event", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.EventRecurrence", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Event", "Event")
                        .WithOne("Recurrence")
                        .HasForeignKey("MyChurch.Domain.Entities.EventRecurrence", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.FeedLike", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.FeedPost", "FeedPost")
                        .WithMany("Likes")
                        .HasForeignKey("FeedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChurch.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedPost");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.FeedPost", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChurch.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Member", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Address", "Address")
                        .WithMany("Members")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Church");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.MemberDocument", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Member", "Member")
                        .WithMany("Documents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Donation", "Donation")
                        .WithMany("Payments")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyChurch.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Donation");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithOne("Subscription")
                        .HasForeignKey("MyChurch.Domain.Entities.Subscription", "ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChurch.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.TransferHistory", b =>
                {
                    b.HasOne("MyChurch.Domain.Entities.Church", "Church")
                        .WithMany()
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Address", b =>
                {
                    b.Navigation("Church")
                        .IsRequired();

                    b.Navigation("Members");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Book", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Chapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Bible.Version", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.CashFlowCategory", b =>
                {
                    b.Navigation("CashFlowEntries");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Church", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("CashFlowCategories");

                    b.Navigation("CashFlowEntries");

                    b.Navigation("Events");

                    b.Navigation("Members");

                    b.Navigation("Subscription")
                        .IsRequired();
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Donation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Event", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Recurrence")
                        .IsRequired();
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.FeedPost", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Member", b =>
                {
                    b.Navigation("CashFlowEntries");

                    b.Navigation("CreditCardInfos");

                    b.Navigation("Documents");

                    b.Navigation("Donations");
                });

            modelBuilder.Entity("MyChurch.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
