// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyChurch.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyChurch.Infrastructure.Migrations
{
    [DbContext(typeof(MyChurchDbContext))]
    [Migration("20260109000100_AddTransfersSchedulingAndBankAccount")]
    partial class AddTransfersSchedulingAndBankAccount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is maintained in `MyChurchDbContextModelSnapshot.cs`.
        }
    }
}
